# Reference card: https://www.appveyor.com/docs/appveyor-yml/
# Validate YAML: https://ci.appveyor.com/tools/validate-yaml

image:
  - Ubuntu1804
  - Visual Studio 2017
clone_script:
  - cmd: git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
  - cmd: git checkout -qf %APPVEYOR_REPO_COMMIT%
  - sh: git clone -q --recursive --branch=${APPVEYOR_REPO_BRANCH} https://github.com/${APPVEYOR_REPO_NAME}.git ${APPVEYOR_BUILD_FOLDER}
  - sh: git checkout -qf ${APPVEYOR_REPO_COMMIT}
install:
  - sh: sudo update-alternatives --set gcc /usr/bin/gcc-8
before_build:
  - sh: g++ --version
  - cmake --version
  - mkdir build
  - cd build
  - cmake ..
build_script:
# See: Building MSVC project with cmake and command-line: https://stackoverflow.com/a/8559426/496459
  - cmake --build . --clean-first
