# Reference card: https://www.appveyor.com/docs/appveyor-yml/
# Validate YAML: https://ci.appveyor.com/tools/validate-yaml

image:
  - Ubuntu1804
  - Visual Studio 2017
install:
  - sh: sudo update-alternatives --set gcc /usr/bin/gcc-8
before_build:
  - git submodule update --init --recursive
  - cmake --version
  - sh: sudo apt-get -y -qq install clang
  - sh: g++ --version && clang++ --version
  - sh: mkdir build_gnu
  - sh: cd build_gnu
  - sh: CXX=g++ CC=gcc cmake ..
  - sh: cd ..
  - sh: mkdir build_llvm
  - sh: cd build_llvm
  - sh: CXX=clang++ CC=clang cmake ..
  - sh: cd ..
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake ..
  - cmd: cd ..
build_script:
  - sh: cmake --build build_gnu --clean-first
  - sh: cmake --build build_llvm --clean-first
# See: Building MSVC project with cmake and command-line: https://stackoverflow.com/a/8559426/496459
  - cmd: cmake --build build --clean-first
