# Reference card: https://www.appveyor.com/docs/appveyor-yml/
# Validate YAML: https://ci.appveyor.com/tools/validate-yaml

image:
  - Ubuntu1804
  - Visual Studio 2017
install:
  - sh: sudo update-alternatives --set gcc /usr/bin/gcc-8
before_build:
  - git submodule update --init --recursive
  - cmake --version
  - mkdir build
  - cd build
  - cmake ..
build_script:
# See: Building MSVC project with cmake and command-line: https://stackoverflow.com/a/8559426/496459
  - cmake --build . --clean-first
